#ifndef ERROR_STATUS_HPP
#define ERROR_STATUS_HPP

namespace error_status
{
enum type
{
   STATUS_OK,
   COMMAND_LINE_PARSER_FAILED,
   COMMAND_LINE_PARAMETER_MISSING,
   COMMAND_LINE_COMPILER_INVALID,
   COMMAND_LINE_PROJECT_INVALID,
   FILE_PARSING_FAILED,
   COMPILATION_FAILED,
   LINKING_FAILED
};
}

#endif //! ERROR_STATUS_HPP